### PR TITLE
Functionality to retrieve the x-csrf-token header from an existing Client session

### PR DESCRIPTION
**Pull request by sur4y**
I needed this functionality in order to retrieve the x-csrf-token header from the current user. After noticing that it [exists in noblox.js](https://noblox.js.org/lib_util_getGeneralToken.js.html), I decided to fork the project & add my own method of getting the token. Perhaps this library can make use of such a functionality?

Let me know if anything needs to be renamed or otherwise changed!

### CODE REVIEW

**Comment by royce-mathew** [comment]
Your pull request contains the modified cargo.toml file from your fork, if you could revert the cargo.toml file to the original and add yourself as a contributor I can merge the pr. Thanks for contributing! I eventually plan to work on the README and eventually write Documentation for all the code.

**Comment by sur4y** [comment]
@royce-mathew Apologies! I didn't know the rest of my commits would edit the rest of the PR. Would you want me to create another PR instead?

**Comment by royce-mathew** [comment]
@sur4y It'd be nice if you could do that, thanks again for contributing!

**Comment by sur4y** [comment]
@royce-mathew Sorry again for the clutter, should I still create a new PR? I believe I've cleaned up what had to be removed, just let me know if I should still create a new PR =]

**Comment by royce-mathew** [comment]
No new PR needed, You should be able to make new commits on your fork now that the pr has been merged

**Comment by sur4y** [comment]
Thank you so much for putting up with me! Have a great day :)

**Pull request merged**
